### ISSUE TITLE
Could `MaybeUninit<T: Copy>` implement `AnyBitPattern`?

### ISSUE THREAD

**Issue by notgull** [Lokathor/bytemuck#108]
It already implements `Zeroable`, and the main draw of `MaybeUninit` is that it can contain theoretically any bit pattern.

**Comment by Lokathor** [comment]
I'm just double checking recent open issues, and that does seem correct at a glance. You don't even need the Copy bound. Any type at all wrapped with MaybeUninit can take on any bit pattern (you just can't safely get it back out).
