### ISSUE TITLE
`Pod` array semantics

### ISSUE THREAD

**Issue by HeroicKatora** [Lokathor/bytemuck#14]
The documentation of [`Pod`](https://docs.rs/bytemuck/1.1.0/bytemuck/trait.Pod.html) list five unsafe requirements¹. However, *not* listed among them is a requirement important for slices of the type. Quoting from the [unsafe code guidelines](https://rust-lang.github.io/unsafe-code-guidelines/layout/arrays-and-slices.html).

> The layout of a slice [T] of length N is the same as that of a [T; N] array. 

> Array types, [T; N], store N values of type T with a constant stride. Here, stride is the distance between each pair of consecutive values within the array.

> The stride of the array is constant for all element pairs and it is computed as the size of the element type rounded up to the next multiple of the alignment of the element type.

Note the distinction between the two stride and slice. Since `cast_slice` and others calculates the length of new array by dividing by the *size* of elements it is important that the *size* and the *stride* are the same for `Pod` types. In particular for `repr(Rust)` types there are no guarantees (although highly unlikely to be the case) that the size is *not* a multiple of the alignment. For `repr(C)`-types and those who transitively are due to `repr(transparent)` this property is naturally true and thus I would not exactly call this requirement a breaking change. However, it should be listed more explicitely in the documentation.

---

Theoretically speaking, it could be valid for Rust to layout `#[repr(packed)] struct Foo(u16, u8)` such that:

* `size_of::<Foo>() == 3`
* `align_of::<Foo>() == 2`
* `stride_of::<Foo>() == 4` (theoretical new function)

The example in the documentation uses `repr(C)` where such a type would have necessarily a size of `4`.

-------

¹ Extracted from behind the link click the link:
* The type must be inhabited (eg: no Infallible).
* The type must allow any bit pattern (eg: no bool or char, which have illegal bit patterns).
* The type must not contain any padding bytes, either in the middle or on the end (eg: no #[repr(C)] struct Foo(u8, u16), which has padding in the middle, and also no #[repr(C)] struct Foo(u16, u8), which has padding on the end).
* The type needs to have all fields also be Pod.
* The type needs to be repr(C), repr(transparent), or repr(packed).

**Comment by Lokathor** [comment]
size == stride for all current rust types because size is always a multiple of alignment in current rust.

Rust _could_ do any future change that would break a lot of people, but I'm not afraid of that happening.

particularly, since there's no `stride_of`, it's impossible to design around that idea.

Basically the UCG text is trying to keep open a door that's almost for sure already closed.

**Comment by HeroicKatora** [comment]
While it's true that this door is *almost* surely closed it seems nevertheless important to list it for now. Probably a short amendment of the last requirement would do. The example above needs to abuse `repr(packed)` to allow smuggle a `repr(rust)` type trough the wording of the documentation :)

**Comment by Lokathor** [comment]
which example with a repr rust type?

**Comment by HeroicKatora** [comment]
This type *would* adhere to the requirements in the documentation *if* rust tuples would be allowed to have size that is not a multiple of the alignment. Let's check them one-by-one.

```rust
#[repr(packed)] // Note: *composes* with the base type, this is not repr(C).
struct Bad(u16, u8);
```



- [x] The type must be inhabited (eg: no Infallible).
    Obviously true.
- [x] The type must allow any bit pattern (eg: no bool or char, which have illegal bit patterns).
    Also true.
- [x] The type must not contain any padding bytes, either in the middle or on the end (eg: no #[repr(C)] struct Foo(u8, u16), which has padding in the middle, and also no #[repr(C)] struct Foo(u16, u8), which has padding on the end).
    
    This is the assumption, that Rust might one day enable this. In the current compiler it does not occur and the struct has padding at the end. But since it is `repr(rust)` this is not guaranteed and if a future version would stabilize this with size `3` then this could be fulfilled.

- [x] The type needs to have all fields also be Pod.
    Also true.
- [x] The type needs to be repr(C), repr(transparent), or repr(packed).
    Indeed it is. I *assume* the documentation was intended to instead allow `repr(packed)` only in conjuction with one of the other base representations.

**Comment by Lokathor** [comment]
oh so packed and C,packed are different?

**Comment by HeroicKatora** [comment]
> oh so packed and C,packed are different?

Indeed, so it seems in the documentation.

**Comment by Lokathor** [comment]
Yeah, then that's kinda dumb but also means i gotta fix the docs.

**Comment by HeroicKatora** [comment]
I'm not quite sure if you actually need to mention the explicit `repr(C)` requirement. More, since `repr(transparent)` relies on the representation of the underlying type one could argue that this enables the same kinds of shenanigans. Rather, I would explicitely state the stride/size as above and make a sidenote that this is impossible to guarantee except by explicitly annotating the type with `repr(C)` or a transparent representation on top of such a type. (Apart for special exceptions such as `Option<NonZeroU8>` which is neither but it has the same representation as a `repr(C)` type so it's fine).

**Comment by Lokathor** [comment]
aside from stride/size, it must be C and not Rust because Rust allows field re-ordering

**Comment by HeroicKatora** [comment]
> aside from stride/size, it must be C and not Rust because Rust allows field re-ordering

How are internal fields a problem to `Pod`? That would be the problem of the programmer applying it. But a packed repr-rust struct is guaranteed to remain padding free even if Rust is allowed to re-order the fields.

**Comment by Lokathor** [comment]
Partly for sanity sake, if a struct has fields a and b written in that order in the source, then you cast it to an array, then arr[0] better be the `a` value.

But mostly I was told that it's just plain UB to, for example, cast &(u16,u16) into &[u16;2], that's just the rules. You cannot inspect or interact with the internals of repr rust except through the proscribed safe ways.

**Comment by HeroicKatora** [comment]
If fields were to change order, that would be very surprising. As far as I've understood there is not even a true commitment that all instances of a particular repr-rust struct have the same order of fields? But the tuple-vs-array example is, as far as I am aware, only because *no* layout of tuples have been specified and they might still have different alignment or padding than arrays so that *unconditionally* casting one to the other is unsound. However, that line of reasoning is different for packed structs, which tuples are not.

But I don't want to get lost in technicalities here, it will in any case be much easier to remove some requirements than it is to add them. So, the sane option is indeed to require `repr(C)` for now.

**Comment by Lokathor** [comment]
Yes, Field order is fixed during compilation and all instances of a type will have the same ordering, but they don't need to match the order you see in the source code.

in other words:
```rust
struct Stuff {
  a: u8,
  b: u16,
  c: u8,
}
```
In this case, `rustc` is _highly likely_ to move the u16 to the start or the end of the struct. And that's already more than I
