### ISSUE TITLE
MSRV and #[cfg(target_has_atomic = "ptr")]

### ISSUE THREAD

**Issue by kali** [Lokathor/bytemuck#142]
Hello, the latest release breaks because it makes use of target_has_atomic, while maintaining a MSRV at 1.34.

According to https://github.com/rust-lang/rust/blob/master/RELEASES.md, target_has_atomic is availbable starting rust 1.60.0.

Please consider fixing it, but also yanking bytemuck 1.12.3 as this is breaking projects maintaining pre-1.60 compatibility.

**Comment by kali** [comment]
LOL, please disregard this.

**Comment by kali** [comment]
OK, just to explain what happens in case somebody falls in the same trap. I'm using transitively bytemuck through the image crate which requires bytemuck feature extern_crate_alloc.

```
bytemuck = { version = "1.7.0", features = ["extern_crate_alloc"] } # includes cast_vec
```

My understanding is that MSRV 1.34 for bytemuck stands for the default feature set only. At least that's what bytemuck CI seems to covers.

**Comment by Lokathor** [comment]
would you mind saying what version of rust you're on?

**Comment by kali** [comment]
My MSRV is 1.59.0 . You can see errors here. https://github.com/sonos/tract/actions/runs/3403898191

Interestingly it seems to be observable only for some cross compilation target (not all of them, and not the linux x64 one).

**Comment by kali** [comment]
Ha, yes, android and ios target do not get the examples build (so the dependency on image is not activated). Not sure why it does not show up on the main native build.

**Comment by kali** [comment]
OK, my main CI does not check the examples. I only build them on cross-platform build. This is a bit absurd, I'm gonna fix this, and the issue should happen on the regular build too.

**Comment by Lokathor** [comment]
It's *possible* to reduce the MSRV by making `Arc` stuff be behind a feature instead, but I didn't want to do that and make everyone have to think about yet another cargo feature when even the Rust in Debian Testing is on 1.61, and that'll become their Stable sometime in 2023.

I'd be interested in trying to have most of `bytemuck` stay at 1.61 or below for a while, but for versions older than 1.61 I think it's reasonable to just upgrade your Rust.

**Comment by kali** [comment]
I will upgrade MSRV pretty soon anyway, but I don't do it on patch version bump.

So I'm just gonna hold bytemuck at 1.12.2 for a couple of weeks.

**Comment by Lokathor** [comment]
Ah, yeah, the problem was that on certain *other* targets (without atomics) then 1.12.2 was also already broken
