### ISSUE TITLE
Docs has no CSS

### ISSUE THREAD

**Issue by DuckDuckWhale** [Lokathor/bytemuck#161]
Only HTML is shown in https://docs.rs/bytemuck/1.12.3/bytemuck/.

**Comment by Lokathor** [comment]
extremely odd. I'll find time to issue a patch to force it to regen the docs and see if that fixes it. Maybe a particular nightly of rustdoc was kinda messed up.

**Comment by Lokathor** [comment]
update: https://rust-lang.zulipchat.com/#narrow/stream/356853-t-docs-rs/topic/bytemuck.20doc.20failing

there was a problem with the nightly that day, and the docs.rs folks are probably gonna fix it on their end.

**Comment by Lokathor** [comment]
fixed by the 1.13 release
