### ISSUE TITLE
The v1.12.4 release might be broken

### ISSUE THREAD

**Issue by lemmih** [Lokathor/bytemuck#165]
The v1.12.4 release refers to `ByteEq` and `ByteHash` which are not part of `bytemuck_derive-1.3.0`. Looks like those macros were added right after `bytemuck_derive-1.3.0` was released.

**Comment by djeedai** [comment]
Same error on CI just now : https://github.com/djeedai/bevy_hanabi/actions/runs/3962602763/jobs/6789466651
Confirmed locally too with a `cargo update`. Reverting to 1.12.3 fixes things.

**Comment by Lokathor** [comment]
bhaaa.

I'll have to yank for now and i can fix this soon

**Comment by Lokathor** [comment]
should be yanked now

**Comment by Lokathor** [comment]
I released bytemuck-derive 1.4, which should make the new derives available.

If nothing is wrong so far, I can release a *minor* version of bytemuck next (1.13) using the new minor version of the derive crate.

**Comment by Lokathor** [comment]
put out 1.13 last night and no one showed up to report more things on fire, so i'm gonna close this.

**Comment by djeedai** [comment]
Thanks @Lokathor !
