### ISSUE TITLE
Should `pod_collect_to_vec()` input type require `AnyBitPattern`?

### ISSUE THREAD

**Issue by MarijnS95** [Lokathor/bytemuck#177]
Disclaimer: I'm still fuzzy on the various traits and their requirements.

`pod_collect_to_vec()` requires `NoUninit + AnyBitPattern` on both the source slice and output `Vec` type. However, casts like `cast_vec` and `cast_slice` only require `NoUninit` on the source type (we can safely read all bytes, but don't need to zero-initialize the source type) and require the full `AnyBitPattern` exclusively on the output type (for `pod_collect_to_vec()`: to first zero-initialize the output `Vec` before copying into it?).

https://github.com/Lokathor/bytemuck/blob/1039388f0baa4532f499c7e809a92dc5552e2edd/src/allocation.rs#L285-L288

Is this constraint desired (and if so, can it be more clearly documented?) or accidental (and can it be relaxed)?

Thanks for this crate by the way! It's solving a bunch of problems for us that have always been looming around the corner :grimacing:

**Comment by Lokathor** [comment]
The reason for the `NoUninit` requirement on the destination type is because of the guts of the function itself:

```rust
pub fn pod_collect_to_vec<
  A: NoUninit + AnyBitPattern,
  B: NoUninit + AnyBitPattern,
>(
  src: &[A],
) -> Vec<B> {
  let src_size = size_of_val(src);
  // Note(Lokathor): dst_count is rounded up so that the dest will always be at
  // least as many bytes as the src.
  let dst_count = src_size / size_of::<B>()
    + if src_size % size_of::<B>() != 0 { 1 } else { 0 };
  let mut dst = vec![B::zeroed(); dst_count];

  let src_bytes: &[u8] = cast_slice(src);
  let dst_bytes: &mut [u8] = cast_slice_mut(&mut dst[..]);
  dst_bytes[..src_size].copy_from_slice(src_bytes);
  dst
}
```

The actual copy from the `Vec<A>` into the new `Vec<B>` happens on two `[u8]` references that are equal sized. However, we can't make both those `[u8]` *references* if either type has uninit bytes.

If we really had to, we could use slice *pointers* instead of slice references, but then the function itself would have to do one or two unsafe calls. Even within `bytemuck`, it's *preferred* when a function doesn't need to open up any unsafe of its own and we can just rely on the other traits/functions.

So, it's not a copy-paste error, but it's also not an absolute requirement of performing this operation. It's possible, in an absolute sense, to relax the restriction, but without a strong and clear motivating case i wouldn't want to relax the restriction "just to do it".

**Comment by MarijnS95** [comment]
> `NoUninit` requirement on the destination type

I should have been more clear and repeated the title once more: my main concern is with the input/source type. After all, `src` is only passed into `cast_slice` which only requires `NoUninit`.

> but without a strong and clear motivating case i wouldn't want to relax the restriction "just to do it".

I don't want to suddenly derive `bytemuck::Pod, bytemuck::Zeroable` on all my types that are currently defined `bytemuck::NoUninit`, if a simpler alternative is to just call `cast_slice(src).to_vec()`. It'd be more in-line with what we are currently using for `cast_slice` and `cast_vec`.

> 
> ```rust
> pub fn pod_collect_to_vec<
>   A: NoUninit + AnyBitPattern,
>   B: NoUninit + AnyBitPattern,
> >(
>   src: &[A],
> ) -> Vec<B> {
>   let src_size = size_of_val(src);
>   // Note(Lokathor): dst_count is rounded up so that the dest will always be at
>   // least as many bytes as the src.
>   let dst_count = src_size / size_of::<B>()
>     + if src_size % size_of::<B>() != 0 { 1 } else { 0 };
>   let mut dst = vec![B::zeroed(); dst_count];
> 
>   let src_bytes: &[u8] = cast_slice(src);
>   let dst_bytes: &mut [u8] = cast_slice_mut(&mut dst[..]);
>   dst_bytes[..src_size].copy_from_slice(src_bytes);
>   dst
> }
> ```
> 
> The actual copy from the `Vec<A>` into the new `Vec<B>` happens on two `[u8]` references that are equal sized. However, we can't make both those `[u8]` _references_ if either type has uninit bytes.

Still fine (and it makes sense) to keep `NoUninit`, it is the `AnyBitPattern` on `A`/`src` that is the culprit.

> If we really had to, we could use slice _pointers_ instead of slice references, but then the function itself would have to do one or two unsafe calls. Even within `bytemuck`, it's _preferred_ when a function doesn't need to open up any unsafe of its own and we can just rely on the other traits/functions.

Fwiw looks like everything compiles just fine without any changes (no `unsafe` additions) beyond dropping `AnyBitPattern` from `A`.

**Comment by Lokathor** [comment]
Ahhhh, I understand the concern now (I think).

Opened https://github.com/Lokathor/bytemuck/pull/178, which I think fixes what you're after.

**Comment by Lokathor** [comment]
> Here I wonder what this additional complexity is for, over just calling .to_vec() on the result from cast_slice(src)?

The way it's written casting both vecs to be bytes and then copying as bytes lets you go up in alignment (eg, u16 to u32) without fail.

**Comment by MarijnS95** [comment]
> Ahhhh, I understand the concern now (I think).
> 
> Opened #178, which I think fixes what you're after.

Yes, that's exactly it! Lots of unrelated changes though, but I found and approved what is relevant :)

> The way it's written casting both vecs to be bytes and then copying as bytes lets you go up in alignment (eg, u16 to u32) without fail.

Right of course, that is what the `Error` and `unwrap` is for (within `(try_)cast_*`). But means the `to_vec()` might be more efficient when we only need to go down, from some `&[T]` to a `Vec<u8>`, by saving on the zero-initialization (which I hope `to_vec()` does not do via `MaybeUninit`... TBD).

**Comment by Lokathor** [comment]
> Lots of unrelated changes though

Clippy is always coming after me with new warnings :(

> But means the to_vec() might be more efficient when we only need to go down, from some &[T] to a Vec<u8>

If you statically know that the alignment won't go up then yeah just using `cast_slice(data).to_vec()` will likely be more efficient.

I seem to recall that this fn was long ago suggested by someone that wanted to go up in alignment (u8 to u32, or maybe it was f32 to f32x4?)

**Comment by MarijnS95** [comment]
Stricter clippy lints are nice at times (keeps getting better and more complete at pointing out code-smells in a codebase) but sometimes overly pedantic and unnecessarily blocking unrelated PRs. Fwiw `uninlined_format_args` was demoted to pedantic.

Yeah we statically know alignment always goes to `u8`, effectively using it as `bytes_of` on a `&[T]`, and then currently needing an owned `Vec` but hope to relax that to a borrow at some point.

> I seem to recall that this fn was long ago suggested by someone that wanted to go up in alignment (u8 to u32, or maybe it was f32 to f32x4?)

That's what I understand from reading the original issue #49 (PR #50). At first I just thought this was a neat helper but now understand its applicability more clearly. I'll use it in places where alignment requirements go up (and where we need an allocation).

**Comment by MarijnS95** [comment]
Oh and @Lokathor, while I have you here there are a few questions that I don't feel like spawning new issues/discussions for (but can definitely do if desired!).

### `NoUninit` on nested structs with arrays

It seems I cannot `derive(NoUninit)` on a struct that uses another `derive(NoUninit)` struct within an array:

```rust
#[repr(C)]
#[derive(Clone, Copy, NoUninit)]
struct Foo(pub u32);

#[repr(C)]
#[derive(Clone, Copy, NoUninit)]
struct Bar {
    my_foo: Foo,
    my_foo_arr: [Foo; 4], // Error: doesn't implement Pod
    blah: u32,
}
```

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=1d5f5e8a37533c81109d18d97b720e61

Is this something to do with https://github.com/Lokathor/bytemuck/pull/141?

### `io::Cursor` helpers etc?

For now I'm writing code along the lines of:

```rust
let mut blah = vec![Blah::zeroed(); num_blah];
stream.read_exact(bytemuck::cast_slice_mut(*mut blah))?;
```

(This is still better than the `vec![0u8; ...]; read_exact(); from_raw_parts()` that was there previously, not caring about alignment)
