### ISSUE TITLE
Derive gives `clippy::extra_unused_type_parameters` warnings

### ISSUE THREAD

**Issue by Kyuuhachi** [Lokathor/bytemuck#180]
The derive macros generate stuff like
```rs
const _: fn() = || {
    #[allow(clippy::missing_const_for_fn)]
    fn check() {
        fn assert_impl<T: ::bytemuck::Pod>() {}
        assert_impl::<u8>();
    }
};
```
which triggers a `clippy::extra_unused_type_parameters` warning. Only way to suppress it is to `#![allow()]` it in the whole module.

**Comment by Jarcho** [comment]
`fn assert_impl<T: ::bytemuck::Pod>() {}` shouldn't be giving a warning in the first place. Only nightly releases from approximately Feb 9-23 should have had that bug.

**Comment by vitvakatu** [comment]
Btw, clippy team fixed this issue, see https://github.com/rust-lang/rust-clippy/issues/11014

**Comment by Lokathor** [comment]
Thanks, then we can close here I guess.
