### ISSUE TITLE
implement `align_to` by hand

### ISSUE THREAD

**Issue by Lokathor** [Lokathor/bytemuck#19]
Apparently `align_to` is spec'd such that you can just fail to do the conversion, and so MIRI for example choose to just fail and return the starting slice every time.

That's crap, and we need to implement a "by hand" version that doesn't fail so that MIRI can't try to give us the run-around.

**Comment by oli-obk** [comment]
Miri can actually do the right thing nowadays, so we should just fix miri. Please open an issue on the miri repo.

**Comment by Lokathor** [comment]
i might be confused. are you saying that miri can do the right thing now but still doesn't?

**Comment by RalfJung** [comment]
Miri can and does do the right thing unless you set `-Zmiri-symbolic-alignment-check` (this landed quite a while ago with https://github.com/rust-lang/miri/pull/1513).

**Comment by Lokathor** [comment]
Wonderful, closing then.
