### ISSUE TITLE
Feature request: Casting owned slices or vec, I.e. Box<[u64]> to Box<[u8]> or Vec<u64> to Vec<u8>

### ISSUE THREAD

**Issue by theforrestli** [Lokathor/bytemuck#227]

**Comment by zachs18** [comment]
You can't go directly from `Box<[u64]>` to Box<[u8]>` due to allocation alognment requirements, but you can use `cast_slice` and then `slice::to_vec` to get an owned vec in a new allocation (and then `Vec::into_boxed_slice` if needed)

**Comment by theforrestli** [comment]
I was really looking for a solution with no copy or new allocation. I didn't know this was impossible. Any suggestions for future reading? Thanks

**Comment by zachs18** [comment]
`bytemuck::allocation::BoxBytes` might fit your use-case, however it *currently* doesn't support casting to/from boxed slices, only boxed Sized types.

**Comment by theforrestli** [comment]
Thanks!
