### ISSUE TITLE
conversion from `&[u8]` to `&[T]`?

### ISSUE THREAD

**Issue by cmyr** [Lokathor/bytemuck#229]
I assume I'm just missing this, but I don't see a conversion function for reinterpreting a byte slice as a slice of some type `T`. Assuming that other invariants are upheld and that `slice.len()` is divisible by `size_of::<T>()` then I think this should be fine. Am I overlooking anything?

**Comment by zachs18** [comment]
This is [`cast_slice`](https://docs.rs/bytemuck/latest/bytemuck/fn.cast_slice.html). Note that it will (correctly) fail if the slice's address is not aligned to `std::mem::align_of::<T>()`.

**Comment by Lokathor** [comment]
Yep.

Best practice is to start with the most aligned type you want a slice of and then `cast_slice` to a less aligned type (if any).

```rust
// using u64 as an example type:
let mut buf = vec![0_u64; 32];
let byte_buf = cast_slice_mut(&mut buf);

copy_u64_data_to_byte_buffer_somehow(byte_buf);

// now `buf` has the updates u64 values.
```

**Comment by cmyr** [comment]
ah okay I was confused thinking that `cast_slice` required a 1:1 correspondence between `A` and `B`. Thanks!
