### ISSUE TITLE
Allow deriving `Zeroable` for enums which are `#[repr(u32, i8, etc..)]`

### ISSUE THREAD

**Issue by ARitz-Cracker** [Lokathor/bytemuck#230]
If an enum is explicitly defined in a manner where "0" is a valid variant, and all the payloads of the 0 variant are zeroable, then it concludes that the enum is safely zeroable.

**Comment by ARitz-Cracker** [comment]
Additionally (though this may be a separate issue) an enum which is `#[repr(u8)]` and has all 256 variants explicitly defined can have `Pod` be safely derived.

**Comment by Lokathor** [comment]
That all sounds right to me.
