### ISSUE TITLE
Support `f16` and `f128` under a nightly flag

### ISSUE THREAD

**Issue by tgross35** [Lokathor/bytemuck#250]
[`f16` and `f128`](https://github.com/rust-lang/rust/issues/116909) have been unstably around for a few months now. It would be great to have them usable via bytemuck for e.g. easy testing with GPUs.

**Comment by Lokathor** [comment]
Yep, I'd merge a PR for this.

**Comment by tgross35** [comment]
Here you go https://github.com/Lokathor/bytemuck/pull/251
