### ISSUE TITLE
TargetAlignmentGreaterAndInputNotAligned

### ISSUE THREAD

**Issue by Soveu** [Lokathor/bytemuck#26]
Maybe we should explain better the difference between `TargetAlignmentGreaterAndInputNotAligned` and `AlignmentMismatch`.
At least for me they are the same error

Where `AlignmentMismatch` is used
`try_from_bytes`
`try_cast_box`
`try_cast_vec`

Where the longer one is used
`try_cast_slice`
`try_cast_ref`

(and also their `_mut` counterparts)

**Comment by Lokathor** [comment]
Closed in https://github.com/Lokathor/bytemuck/commit/4f2a822cb691ba18a748aea31f6bb6bc36eb7a09
