### ISSUE TITLE
Same code behaves differently when compiled with debug and release (UB?)

### ISSUE THREAD

**Issue by matheus-consoli** [Lokathor/bytemuck#282]
I was helping a friend with some code, and I think he found a UB.

The code in the playground behaves differently depending on the profile it's compiled on, and if a `dbg` call is presented or not.

```org-mode
|             | debug | release | miri  |
| without dbg | panic | works   | panic |
| with dbg    | works | works   | panic |
```

to be clear, miri doesn't say it's UB; the code panics while running in its VM.

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=04202edbc701eaf9d89d8ea4f40fcd41

**Comment by Lokathor** [comment]
`cast_ref` will panic if the reference isn't sufficiently aligned. Using debug or release can do any number of optimizations that *may* affect the alignment of the source `[0u8; 64]` value. When you cast a reference into that array to being a `&u128` reference, it increases the required alignment. Sometimes the source array will be sufficiently aligned to let it work, other times it won't be high enough aligned.
