### ISSUE TITLE
`latest_stable_rust` feature is out of date

### ISSUE THREAD

**Issue by Lokathor** [Lokathor/bytemuck#288]
`alloc_uninit`, `transparentwrapper_extra`, and possibly other features that work on stable are *not* currently in the `latest_stable_rust` feature (which they should be).

**Comment by zachs18** [comment]
`alloc_uninit` is in the `latest_stable_rust` already, it just doesn't do anything if `extern_crate_alloc` is not also enabled, and `latest_stable_rust` doesn't include `extern_crate_alloc` (explicitly).

For future[^1] features which depend both on higher MSRV *and* `alloc`/`std`, I see two options:
1. Have them be in `latest_stable_rust`, and have them just do nothing if `extern_crate_alloc`/`extern_crate_std` is not enabled (status quo for `alloc_uninit`)
2. Have them *not* in `latest_stable_rust`, and have them depend on `extern_crate_alloc`/`extern_crate_std`
   a. Perhaps have new `latest_stable_rust_alloc = ["latest_stable_rust", "extern_crate_alloc", "alloc_uninit", ...]`, `latest_stable_rust_std = ["latest_stable_rust_alloc",  "extern_crate_std", ...]` features that enable all latest-stable features including ones that require `alloc`/`std`.


---

I looked, and it seems like other than `transparentwrapper_extra`, all other existing, sound, non-nightly, non-`extern_crate_alloc/std` features are included in `latest_stable_rust`, so I'll make a PR to add `transparentwrapper_extra` to `latest_stable_rust`.
   
[^1]: at this point I think it would be a breaking change to make `alloc_uninit` use option 2
