### ISSUE TITLE
[Breaking] Change definition of TransparentWrapper

### ISSUE THREAD

**Issue by Soveu** [Lokathor/bytemuck#29]
Because it does not make sense to implement many `TransparentWrapper`s for one struct I suggest changing the definition to
```rust
pub unsafe trait TransparentWrapper {
    type Wrapped: ?Sized;

    fn wrap_ref(s: &Wrapped) -> &Self { ... }
    fn wrap_mut(s: &mut Wrapped) -> &mut Self { ... }
}
```

**Comment by Lokathor** [comment]
Well, I don't see what advantage that gives though.

**Comment by Lokathor** [comment]
@Soveu i'm going to close this in a while if you can't explain what you meant or why this breaking change would be an improvement.
