### ISSUE TITLE
Split `Pod` into two traits

### ISSUE THREAD

**Issue by zakarumych** [Lokathor/bytemuck#41]
Traits `NoPadding` and `AnyBitPattern` that would allow "casting" like this

```
fn cast<T, U>(T) -> U
where
    T: NoPadding,
    U: AnyBitPattern,
{
   ...
}
```

Then `Pod` is simply both.

**Comment by zakarumych** [comment]
As a simple use-case, this will enable us to reinterpret structures with `bool` as bytes.

**Comment by Lokathor** [comment]
When the 1.0 of this crate was being developed, no one considered the ability to view a `&bool` as a `&u8` very valuable, so this particular trait split was skipped on.

I think this would be a breaking change to fit in to the existing crate.

Because of the safe transmute project, any work on a 2.0 is being held off until that project is done and stabilized. However, at that time we might be able to split up the traits like this.

**Comment by zakarumych** [comment]
Would it be a breaking change though?
Relaxing requirements on functions doesn't seem to break anything.

If we add blanket impls like this:

```
impl<T: Pod> NoPadding {}
impl<T: Pod> AnyBitPattern {}
```

instead of the other way around then all existing implementation would still work.

**Comment by Lokathor** [comment]
I admit I'm not a trait expert, so with careful design it might be done I suppose.

I'll point some of the trait folks I know at this topic and maybe they can weigh in.

**Comment by zakarumych** [comment]
Once again I'd really like this feature, as I want to cast bytes to other types which can have padding but accept any bit pattern.

**Comment by Lokathor** [comment]
We could have a NoPadding trait that lets you turn &A into &[u8], and just have it as a separate thing from Pod. That wouldn't be a breaking change.

**Comment by zakarumych** [comment]
And currently I need the reverse. Turning `&[u8]` into `A: AnyBitPattern`.
Although `NoPadding` has its use cases as well.
Do you still think proposed solution above may be a breaking change?

**Comment by Lokathor** [comment]
Yeah. No one I spoke to thought that it was possible to insert and extra trait into the trait tree.

**Comment by zakarumych** [comment]
I'm curious. Did they provide a counterexample?

**Comment by Lokathor** [comment]
No one showed that it couldn't be done, but no one definitely showed it can be done with absolutely no chance of breaks.

I'd rather just have a separate trait, which is assured to not break any existing code.

**Comment by zakarumych** [comment]
Do you mean that you want separate functions as well?

**Comment by Lokathor** [comment]
Yes, we should add this as just a separate group of traits and functions. No breakage that way.

**Comment by Lokathor** [comment]
This has been done as much as will happen in version 1.

Version 2 of the crate will be largely defined by how the safe-transmute project works out, so it's hard to say precisely, but this is expected to be possible at that time.

For now I'm gonna close it.
