### ISSUE TITLE
please include LICENSE-* texts in published _derive crates as well

### ISSUE THREAD

**Issue by decathorpe** [Lokathor/bytemuck#46]
The published bytemuck_derive crates don't contain license files. For most licenses (including MIT), it is usually necessary to include the text of the license itself.

Please consider adding those files to the _derive crate as well. If you're `cargo publish`ing from UNIX-like systems, adding symlinks like `LICENSE-APACHE → ../LICENSE-APACHE` in the `derive` folder should do the trick.

PS: If you will add back the `.md` extensions at some point (as hinted at in the PR that added/renamed the files), keep in mind that you will have to update those symlinks.

**Comment by Lokathor** [comment]
I'd accept a PR that fixes this problem, but my Rust time has been limited lately so I'm honestly unlikely to do this myself any time before the end of the year.

**Comment by decathorpe** [comment]
Thank you for merging! :+1:

**Comment by Lokathor** [comment]
Should also be up on crates.io now (`bytemuck_derive-1.0.1`)
