### ISSUE TITLE
A way to mark repr(transparent) as Pod without unsafe

### ISSUE THREAD

**Issue by RazrFalcon** [Lokathor/bytemuck#48]
Let's say I have a type:
```rust
#[repr(transparent)]
#[derive(Copy, Clone)]
struct MyType(u32);
```

Is there a way to mark it as Pod without unsafe and proc-macros?

**Comment by Lokathor** [comment]
nope. you need one or the other basically.

**Comment by RazrFalcon** [comment]
Thanks. I thought that there is is way to use `bytemuck` and `#![forbid(unsafe_code)]`
