### ISSUE TITLE
bytes_of and bytes_of_mut run into unreachable code when T is a ZST

### ISSUE THREAD

**Issue by lizhuohua** [Lokathor/bytemuck#52]
Hi, I noticed that the documentation of both `bytes_of` and `bytes_of_mut` says:
> Any ZST becomes an empty slice

But instead of returning an empty slice, it actually causes a runtime panic. E.g., when executing:
```rust
use bytemuck;
fn main() {
    let zst: [u32; 0] = [];
    let _result = bytemuck::bytes_of(&zst);  // Panic: entered unreachable code
}
```

**Comment by Lokathor** [comment]
Well spotted. I'll try to fix this later today.
