### ISSUE TITLE
Field's implement traits check fails when using local checkout of bytemuck

### ISSUE THREAD

**Issue by skorpi-and-friends** [Lokathor/bytemuck#56]
That is, when we're using `path` in `Cargo.toml` to point at a local checkout.

Specifically when the fields are types from [glam](https://github.com/bitshifter/glam-rs). Which is on bytemuck version 1.4. Everything's dandy if the field types are locally definded.

[minmal reproduction repo](https://github.com/skorpi-and-friends/bytemuck_glam_test)

Intended behavior? Anything I can do?

**Comment by Lokathor** [comment]
I think this has to do with there being two versions of bytemuck: <https://github.com/skorpi-and-friends/bytemuck_glam_test/blob/main/Cargo.lock#L5-L16>

* `glam` is implementing the crates.io version
* you're trying to implement the `path` version

These are "not actually the same", under cargo compatibility law.

**Comment by skorpi-and-friends** [comment]
Makes sense. I'll  clone glam and carry on. Thank you.
