### ISSUE TITLE
Outdated note about `Zeroable` derive in README?

### ISSUE THREAD

**Issue by LukasKalbertodt** [Lokathor/bytemuck#77]
I'm confused by this part of the README:

> There is experimental support for the `Zeroable` trait being derived through a proc-macro. I'm not the author of that crate, please file bugs with that crate in the other repo.
>
> https://github.com/rodrimati1992/zeroable_crates

To me it looks like the `Zeroable` derive is implemented in this repo. And I also don't see any dependencies to that crate anywhere. Is that note just outdated?

**Comment by Lokathor** [comment]
yeah, readme is old i guess.
