### ISSUE TITLE
Derives for `Eq` and `Hash`

### ISSUE THREAD

**Issue by CryZe** [Lokathor/bytemuck#81]
It probably makes sense to provide derives for `Eq` (and `PartialEq`) and `Hash` in bytemuck. On a `Pod` type `Eq` can be a simple memcmp / bcmp. Hashing is also much more efficient as you can provide all bytes at once.

**Comment by Lokathor** [comment]
Hm. I'm not against this, but I'll also note that `f32` is pod, but a memcmp wouldn't be accurate for 0.0 and -0.0 (which are supposed to be equal).

**Comment by CryZe** [comment]
Yeah, maybe the derives could be named ByteEq, ByteHash or so to clarify that?
